/*list of plant-level variables to keep*/
%let plantchars_keep_all = 
CNAE20_CLASS
ESTAB_SIZE_DEC31
ESTAB_TYPE
LEGAL_NATURE_CONCLA2002
MUNI
;

/*match characteristics to keep in all years*/
%let matchchars_keep_all = 
AGE
CAUSE_OF_SEP
CONTRACT_SALARY
CONTRACT_TYPE
EARN_AVG_MONTH_MW
EARN_AVG_MONTH_NOM
EARN_DEC_MW
EARN_DEC_NOM
EDUC
EMP_ON_DEC31
FINAL_PAY_YEAR
GENDER
HIRE_DATE
MONTH_OF_SEP
NUM_HOURS_CONTRACTED
OCCUP_CBO2002
RACE
SALARY_TYPE
TENURE_MONTHS
WORKER_DISABLED
TYPE_OF_HIRE
;

%let monthly_pay = 
JAN_PAY FEB_PAY MAR_PAY APR_PAY MAY_PAY JUN_PAY JUL_PAY AUG_PAY SEP_PAY OCT_PAY;