%let freqvarlist2017 = 
    MUNI
    CNAE95_CLASS
    EMP_ON_DEC31
    CONTRACT_TYPE
    CAUSE_OF_SEP
    MONTH_OF_SEP
    IND_VINC_ALVARA
    TYPE_OF_HIRE
    SALARY_TYPE
    OCCUP_CBO94
    EDUC_v2005
    SEX
    NATIONALITY
    RACE_v2006
    WORKER_DISABLED
    ESTAB_SIZE_DEC31
    LEGAL_NATURE_CONCLA2002
    WORKER_LINKED_CEI
    ESTAB_TYPE
    ESTAB_IN_PAT
    IND_SIMPLES
    HIRE_DATE
    NUM_HOURS_CONTRACTED
    /* PIS */
    DATE_OF_BIRTH
    /* CTPS */
    /* CPF */
    /* CEI_CONTRACT_ESTAB */
    /* PLANT_ID */
    /* CNPJ_ROOT */
    /* WORKER_NAME */
    OCCUP_CBO2002
    CNAE20_CLASS
    /* CNAE20_SUBCLASS */
    TYPE_OF_DISABILITY
    LEAVE_1_CAUSE
    LEAVE_1_INI_DAY
    LEAVE_1_INI_MON
    LEAVE_1_END_DAY
    LEAVE_1_END_MON
    LEAVE_2_CAUSE
    LEAVE_2_INI_DAY
    LEAVE_2_INI_MON
    LEAVE_2_END_DAY
    LEAVE_2_END_MON
    LEAVE_3_CAUSE
    LEAVE_3_INI_DAY
    LEAVE_3_INI_MON
    LEAVE_3_END_DAY
    LEAVE_3_END_MON
    NUM_LEAVE_DAYS
    AGE
    DAY_OF_SEP
    /* IBGE_SUBSECTOR */
    YEAR_OF_ARRIVAL
    /* CEP_OF_ESTAB */
    WORKER_MUNI
    /* COMPANY_NAME */
    YEAR_OF_ARRIVAL
    PARTIAL_CONTRACT
    INTERMITTENT_CONTRACT
    WORKER_IN_UNION
;

%let univarlist2017=
    EARN_AVG_MONTH_NOM
    EARN_AVG_MONTH_MW
    EARN_DEC_NOM
    EARN_DEC_MW
    TENURE_MONTHS
    JAN_PAY
    FEB_PAY
    MAR_PAY
    APR_PAY
    MAY_PAY
    JUN_PAY
    JUL_PAY
    AUG_PAY
    SEP_PAY
    OCT_PAY
    NOV_PAY
    FINAL_PAY_YEAR
    CONTACT_SALARY
;

/*****************************************************************************/
%let freqvarlist2017 = 
    MUNI
    CNAE95_CLASS
    EMP_ON_DEC31
    CONTRACT_TYPE
    CAUSE_OF_SEP
    MONTH_OF_SEP
    IND_VINC_ALVARA
    TYPE_OF_HIRE
    SALARY_TYPE
    OCCUP_CBO94
    EDUC_v2005
    SEX
    NATIONALITY
    RACE_v2006
    WORKER_DISABLED
    ESTAB_SIZE_DEC31
    LEGAL_NATURE_CONCLA2002
    WORKER_LINKED_CEI
    ESTAB_TYPE
    ESTAB_IN_PAT
    IND_SIMPLES
    HIRE_DATE
    NUM_HOURS_CONTRACTED
    /* PIS */
    DATE_OF_BIRTH
    /* CTPS */
    /* CPF */
    /* CEI_CONTRACT_ESTAB */
    /* PLANT_ID */
    /* CNPJ_ROOT */
    /* WORKER_NAME */
    OCCUP_CBO2002
    CNAE20_CLASS
    /* CNAE20_SUBCLASS */
    TYPE_OF_DISABILITY
    LEAVE_1_CAUSE
    LEAVE_1_INI_DAY
    LEAVE_1_INI_MON
    LEAVE_1_END_DAY
    LEAVE_1_END_MON
    LEAVE_2_CAUSE
    LEAVE_2_INI_DAY
    LEAVE_2_INI_MON
    LEAVE_2_END_DAY
    LEAVE_2_END_MON
    LEAVE_3_CAUSE
    LEAVE_3_INI_DAY
    LEAVE_3_INI_MON
    LEAVE_3_END_DAY
    LEAVE_3_END_MON
    NUM_LEAVE_DAYS
    AGE
    DAY_OF_SEP
    /* IBGE_SUBSECTOR */
    YEAR_OF_ARRIVAL
    /* CEP_OF_ESTAB */
    WORKER_MUNI
    /* COMPANY_NAME */
    YEAR_OF_ARRIVAL
    PARTIAL_CONTRACT
    INTERMITTENT_CONTRACT
    WORKER_IN_UNION
;

%let univarlist2016=
    EARN_AVG_MONTH_NOM
    EARN_AVG_MONTH_MW
    EARN_DEC_NOM
    EARN_DEC_MW
    TENURE_MONTHS
    JAN_PAY
    FEB_PAY
    MAR_PAY
    APR_PAY
    MAY_PAY
    JUN_PAY
    JUL_PAY
    AUG_PAY
    SEP_PAY
    OCT_PAY
    NOV_PAY
    FINAL_PAY_YEAR
    CONTACT_SALARY
;
